INSERT INTO RAMO
VALUES(NEXTVAL('HIBERNATE_SEQUENCE'), 1, 'vida');

INSERT INTO RAMO
VALUES(NEXTVAL('HIBERNATE_SEQUENCE'), 2, 'acidentes');

INSERT INTO RAMO
VALUES(NEXTVAL('HIBERNATE_SEQUENCE'), 3, 'salud');

INSERT INTO RAMO
VALUES(NEXTVAL('HIBERNATE_SEQUENCE'), 4, 'retiro');

INSERT INTO ASEGURADO (ID, DIRECCION, EDAD, NOMBRE)
VALUES(1, 'JDJ 432', 34, 'Lucas Diaz');

INSERT INTO ASEGURADO (ID, DIRECCION, EDAD, NOMBRE)
VALUES(2, 'PD 901', 23, 'Sofia Velez');
