INSERT INTO ASEGURADO (ID, DIRECCION, EDAD, NOMBRE)
VALUES(1, 'JDJ 432', 34, 'Lucas Diaz');

INSERT INTO ASEGURADO (ID, DIRECCION, EDAD, NOMBRE)
VALUES(2, 'PD 901', 23, 'Sofia Velez');

INSERT INTO COBERTURA 
VALUES(1, 'Vida Total', 'VIDA');

INSERT INTO COBERTURA 
VALUES(2, 'Vida Ahorro', 'VIDA');

INSERT INTO COBERTURA 
VALUES(3, 'Vida Temporal', 'VIDA');

INSERT INTO COBERTURA 
VALUES(4, 'Deportistas', 'AP');

INSERT INTO COBERTURA 
VALUES(5, 'Trabajo', 'AP');

INSERT INTO COBERTURA 
VALUES(6, 'Profesionales', 'AP');

INSERT INTO POLIZA 
VALUES(1, 'Debito', 500000, 1, 1 );

INSERT INTO POLIZA 
VALUES(4, 'Debito', 250000, 2, 4 );
